# Site settings
title: "Resume"
description: Resume template using Jekyll

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
  
# Resume settings
resume_avatar:                "false"
resume_name:                  "Michael F. Sloves"
resume_title:                 "Software Engineering Management Professional"
resume_contact_email:         "michaelsloves@gmail.com"
resume_contact_address:       "20 Teak Ct, Medford, NJ 08055"
resume_contact_phone:         "(856)296-3492"
resume_looking_for_work:      "no"

resume_section_summary:       "true"
resume_section_experience:    "true"
resume_section_education:     "true"
resume_section_projects:      "false"
resume_section_skills:        "true"
resume_section_recognition:   "false"
resume_section_links:         "false"
resume_section_associations:  "false"

resume_social_links:
  resume_linkedin_url:        "https://www.linkedin.com/in/michaelsloves"
#  resume_github_url:          "https://github.com/sloveez"

# Design settings
resume_theme:                 "default"
